<script setup>
import { ref } from 'vue'
import { FlaskConical, Play, Download, CheckCircle2, XCircle, LoaderCircle } from 'lucide-vue-next'
import { api, downloadJson } from '../lib/api'
const props = defineProps({ workspace: Object })
const question = ref('购买三天后想退款，应该如何申请？'), intent = ref('refund'), mode = ref('intent'), busy = ref(false), report = ref(null), error = ref('')
const intents = ['refund', 'invoice', 'order_status', 'logistics', 'technical_login', 'technical_crash', 'payment_issue', 'greeting', 'query', 'other']
async function run() { busy.value = true; error.value = ''; report.value = null; try { report.value = await api('/eval/run', { method: 'POST', body: mode.value === 'intent' ? { intent_cases: [{ message: question.value, expected_intent: intent.value }], dialog_cases: [] } : { intent_cases: [], dialog_cases: [{ question: question.value }] } }); props.workspace.notify('评测完成'); await props.workspace.refresh() } catch (e) { error.value = e.message } finally { busy.value = false } }
const labels = { relevance: '相关性', accuracy: '准确性', completeness: '完整性', helpfulness: '有用性', intent_accuracy: '意图准确率' }
</script>
<template><div class="standard-page"><div class="page-heading"><div><div class="eyebrow">EVALUATION LAB</div><h1>评测实验<span class="heading-dot">.</span></h1><p>用一个可复现的测试，理解 Agent 的表现。</p></div><span class="tag neutral">单案例 · 按需执行</span></div><div class="evaluation-grid"><section class="surface"><div class="section-heading"><h2>设计一项实验</h2><FlaskConical :size="20" class="muted" /></div><div class="segmented"><button :class="{ active: mode === 'intent' }" @click="mode = 'intent'">意图识别</button><button :class="{ active: mode === 'quality' }" @click="mode = 'quality'">回复质量</button></div><form @submit.prevent="run"><label class="field">测试问题<textarea v-model="question" rows="5" required maxlength="8000"></textarea></label><label v-if="mode === 'intent'" class="field">预期意图<select v-model="intent"><option v-for="item in intents" :key="item" :value="item">{{ item }}</option></select></label><div class="subtle-note">{{ mode === 'intent' ? '检查预测意图与预期标签是否一致。' : 'Agent 生成回复后，由模型评判相关性、准确性、完整性与有用性。' }} 此操作会调用模型，费用由模型服务商计算。</div><button class="primary full-width" :disabled="busy || !question.trim()"><LoaderCircle v-if="busy" :size="17" class="spin" /><Play v-else :size="16" />{{ busy ? '正在运行评测…' : '运行这项实验' }}</button></form><div v-if="error" class="error-box" role="alert">{{ error }}</div></section><section class="surface report-surface"><div class="section-heading"><h2>实验结果</h2><button class="quiet" :disabled="!report" @click="downloadJson('epochflow-evaluation.json', report)"><Download :size="15" /> 导出</button></div><div v-if="!report" class="retrieval-empty"><FlaskConical :size="38" :stroke-width="1.2" /><h3>{{ busy ? '实验正在进行' : '等待你的第一项实验' }}</h3><p>结果来自实际执行，不预填分数。</p></div><template v-else><div class="report-summary"><strong>{{ Math.round(report.pass_rate * 100) }}<small>%</small></strong><div>通过率<p>{{ report.passed }} / {{ report.total }} 项通过</p></div></div><div class="score-grid"><div v-for="(score, key) in report.avg_scores" :key="key"><span>{{ labels[key] || key }}</span><strong>{{ (score * 100).toFixed(1) }}%</strong><div class="score-track"><i :style="{ width: `${Math.min(100, score * 100)}%` }"></i></div></div></div><article v-for="result in report.results" :key="result.test_id" class="evaluation-result"><component :is="result.passed ? CheckCircle2 : XCircle" :size="19" :class="result.passed ? 'success-text' : 'danger'" /><div><strong>{{ result.test_id }}</strong><p>{{ result.detail }}</p><details v-if="result.metadata"><summary>查看案例与判定依据</summary><pre>{{ JSON.stringify(result.metadata, null, 2) }}</pre></details></div></article><div v-if="report.recommendations?.length" class="subtle-note"><strong>改进建议</strong><p v-for="item in report.recommendations" :key="item">{{ item }}</p></div></template></section></div></div></template>
