<script setup>
import { ref, computed, onMounted } from 'vue'
import { Search, Plus, Upload, FileText, Download, Trash2, X, Library, LoaderCircle } from 'lucide-vue-next'
import { api, downloadJson } from '../lib/api'
const props = defineProps({ workspace: Object })
const documents = ref([]), results = ref(null), query = ref(''), filter = ref(''), loading = ref(false), error = ref(''), adding = ref(false), title = ref(''), content = ref(''), selected = ref(null), deleting = ref('')
const visible = computed(() => documents.value.filter(doc => doc.title.includes(filter.value)))
async function load() { try { documents.value = (await api('/knowledge/documents')).items; error.value = '' } catch (e) { error.value = e.message } }
async function search() { if (!query.value.trim()) return; loading.value = true; error.value = ''; try { results.value = (await api(`/search?query=${encodeURIComponent(query.value)}&top_k=5`, { method: 'POST' })).results } catch (e) { error.value = e.message } finally { loading.value = false } }
async function add() { loading.value = true; error.value = ''; try { await api('/knowledge/add', { method: 'POST', body: { documents: [{ title: title.value, content: content.value }] } }); adding.value = false; title.value = ''; content.value = ''; await load(); props.workspace.notify('知识文档已加入本次运行') } catch (e) { error.value = e.message } finally { loading.value = false } }
async function upload(event) { const file = event.target.files[0]; event.target.value = ''; if (!file) return; if (file.size > 1024 * 1024) { error.value = '文件不能超过 1MB'; return }; const form = new FormData(); form.append('file', file); loading.value = true; try { await api('/knowledge/upload', { method: 'POST', body: form }); await load(); props.workspace.notify('文件导入完成') } catch (e) { error.value = e.message } finally { loading.value = false } }
async function remove(id) { loading.value = true; try { await api(`/knowledge/documents/${id}`, { method: 'DELETE' }); deleting.value = ''; selected.value = null; results.value = null; await load(); props.workspace.notify('文档已从当前运行移除') } catch (e) { error.value = e.message } finally { loading.value = false } }
onMounted(load)
</script>
<template><div class="standard-page"><div class="page-heading"><div><div class="eyebrow">KNOWLEDGE SPACE</div><h1>知识空间<span class="heading-dot">.</span></h1><p>为 Agent 提供依据，让回答有迹可循。</p></div><button class="primary" @click="adding = true"><Plus :size="16" /> 添加文档</button></div>
  <div class="info-banner"><Library :size="18" /><div><strong>轻量检索，真实依据</strong><p>免费版使用字符 n-gram 文本匹配。上传内容仅保留至服务休眠或重启，重要资料请导出保存。</p></div><button class="quiet" :disabled="!documents.length" @click="downloadJson('epochflow-knowledge.json', documents.map(({title, content}) => ({title, content})))"><Download :size="16" /> 导出知识</button></div>
  <div v-if="error" class="error-box" role="alert">{{ error }}</div>
  <div class="knowledge-grid"><section class="surface"><div class="section-heading"><div><span class="eyebrow">COLLECTION</span><h2>文档集 <span class="count">{{ documents.length }}</span></h2></div><label class="quiet upload-label"><Upload :size="16" /> 导入<input type="file" accept=".txt,.md,.json" @change="upload" :disabled="loading" /></label></div><div class="input-with-icon"><Search :size="16" /><input v-model="filter" aria-label="筛选文档" placeholder="按标题筛选文档…" /></div><div class="document-list"><button v-for="doc in visible" :key="doc.id" class="document-row" @click="selected = doc"><span class="document-icon"><FileText :size="20" /></span><span><strong>{{ doc.title || '未命名文档' }}</strong><small>{{ doc.chunks }} 个片段 · {{ doc.content.length }} 字符</small></span><span class="tag neutral">{{ doc.seed ? '预置' : '本次上传' }}</span></button><div v-if="!visible.length" class="empty-small">暂无匹配文档。试着添加第一篇资料。</div></div><p class="panel-footnote">支持 TXT、Markdown、JSON，每个文件不超过 1MB。</p></section>
  <section class="surface"><div class="section-heading"><div><span class="eyebrow">RETRIEVAL PLAYGROUND</span><h2>试一试检索</h2></div><Search :size="21" class="muted" /></div><p class="muted small">输入一个问题，检查 Agent 能找到哪些资料。</p><form class="search-form" @submit.prevent="search"><input v-model="query" aria-label="知识检索问题" placeholder="例如：退款审核需要多久？" maxlength="8000" /><button class="primary" :disabled="loading || !query.trim()"><LoaderCircle v-if="loading" :size="17" class="spin" /><Search v-else :size="17" /></button></form><div v-if="results === null" class="retrieval-empty"><Search :size="32" :stroke-width="1.2" /><h3>先检索，再提问</h3><p>观察问题与资料之间的匹配关系。</p></div><template v-else><div class="results-label">找到 {{ results.length }} 个匹配片段 <span>TEXT MATCH</span></div><article v-for="(result, index) in results" :key="index" class="search-result"><div><strong>{{ result.title }}</strong><span class="tag">{{ (result.score * 100).toFixed(1) }}% 相似度</span></div><p>{{ result.content }}</p></article><div v-if="!results.length" class="empty-small">没有匹配资料。可以换个关键词，或添加相关文档。</div></template></section></div>
  <div v-if="adding || selected" class="modal-backdrop" @click.self="adding = false; selected = null"><section class="modal" role="dialog" aria-modal="true" :aria-label="adding ? '添加知识文档' : '文档详情'"><div class="section-heading"><h2>{{ adding ? '添加知识文档' : selected.title }}</h2><button class="icon-button" aria-label="关闭" @click="adding = false; selected = null"><X :size="19" /></button></div><form v-if="adding" @submit.prevent="add"><label class="field">文档标题<input v-model="title" required maxlength="500" placeholder="例如：售后退款政策" /></label><label class="field">文档内容<textarea v-model="content" rows="10" required maxlength="100000" placeholder="粘贴 Agent 回答时需要参考的资料…"></textarea></label><div v-if="error" class="error-box">{{ error }}</div><div class="modal-actions"><span class="small muted">资料仅在本次服务运行中保存</span><button class="primary" :disabled="loading">{{ loading ? '正在保存…' : '添加文档' }}</button></div></form><template v-else><pre class="document-content">{{ selected.content }}</pre><div class="modal-actions"><span class="small muted">{{ selected.chunks }} 个片段</span><button v-if="deleting !== selected.id" class="quiet danger" @click="deleting = selected.id"><Trash2 :size="15" /> 移除文档</button><button v-else class="primary danger-button" :disabled="loading" @click="remove(selected.id)">确认从本次运行移除</button></div></template></section></div>
</div></template>
