<script setup>
import { computed } from 'vue'
import { RefreshCw, ArrowRight, Bot, Activity, BookOpen, Workflow } from 'lucide-vue-next'
const props = defineProps({ workspace: Object })
const { health, monitor, skills, refresh } = props.workspace
const agents = computed(() => Object.entries(monitor.value?.agent_stats || health.value?.agents || {}))
const requests = computed(() => agents.value.reduce((sum, [, item]) => sum + item.total, 0))
const roles = { general: '通用咨询', technical: '技术支持', billing: '账单与退款', escalation: '人工交接' }
</script>
<template><div class="standard-page"><div class="page-heading"><div><div class="eyebrow">OBSERVE & UNDERSTAND</div><h1>运行概览<span class="heading-dot">.</span></h1><p>理解系统的组成，也看见它当下的状态。</p></div><button class="secondary" @click="refresh"><RefreshCw :size="15" /> 刷新状态</button></div><div class="stat-grid"><div class="stat-card"><span>Agent 实例</span><strong>{{ agents.length || '—' }}</strong><small>按能力路由与协作</small></div><div class="stat-card"><span>本次运行调用</span><strong>{{ requests }}</strong><small>包含对话和评测调用</small></div><div class="stat-card"><span>已加载 Skills</span><strong>{{ skills?.count ?? '—' }}</strong><small>按需注入业务规则</small></div><div class="stat-card"><span>数据模式</span><strong class="stat-word">临时内存</strong><small>免费运行 · 无持久磁盘</small></div></div><section class="surface architecture"><div class="section-heading"><div><span class="eyebrow">HOW IT WORKS</span><h2>让一次请求，变成一次可观察的协作</h2></div><Workflow :size="23" /></div><div class="architecture-flow"><template v-for="(stage, index) in [['输入与记忆','带入最近的会话上下文'],['意图识别','识别问题类型与关键信息'],['Agent 路由','选择通用、技术或账单能力'],['工具与知识','按需检索、执行并生成回复']]" :key="index"><div><span>0{{ index + 1 }}</span><h3>{{ stage[0] }}</h3><p>{{ stage[1] }}</p></div><ArrowRight v-if="index < 3" :size="18" /></template></div><p class="panel-footnote">以客服场景呈现 Agent 工程链路。预置订单、退款等业务工具为脱敏演示数据，不连接真实商家系统。</p></section><div class="overview-columns"><section class="surface"><div class="section-heading"><h2>Agent 能力</h2><Bot :size="20" class="muted" /></div><div v-for="([id, item]) in agents" :key="id" class="agent-row"><span class="agent-icon"><Bot :size="18" /></span><div><strong>{{ roles[id.replace(/_\d+$/, '')] || item.role }}</strong><small>{{ item.total }} 次调用 · {{ item.total ? (item.success_rate * 100).toFixed(0) + '% 成功' : '尚无调用' }}</small></div><span class="tag neutral">{{ id }}</span></div><p v-if="!agents.length" class="empty-small">连接后端后查看能力。</p></section><section class="surface"><div class="section-heading"><h2>Skills 规则集</h2><BookOpen :size="20" class="muted" /></div><article v-for="skill in skills?.skills || []" :key="skill.id || skill.name" class="skill-item"><strong>{{ skill.name }}</strong><p>{{ skill.description || '按匹配的业务问题注入 Agent 上下文。' }}</p><div class="tag-row"><span v-for="keyword in (skill.keywords || []).slice(0, 5)" :key="keyword" class="tag neutral">{{ keyword }}</span></div></article><p v-if="!skills?.count" class="empty-small">尚未加载规则集。</p></section></div></div></template>
