<script setup>
import { ref } from 'vue'
import { KeyRound, Server, ShieldCheck, RefreshCw, CheckCircle2, ExternalLink } from 'lucide-vue-next'
import { apiBase, token, setToken } from '../lib/api'
const props = defineProps({ workspace: Object })
const { health, refresh, notify } = props.workspace
const accessToken = ref(token()), saving = ref(false)
async function save() { saving.value = true; setToken(accessToken.value); await refresh(); saving.value = false; if (!props.workspace.connectionError.value) notify('访问设置已保存，后端连接正常') }
</script>
<template><div class="standard-page settings-page"><div class="page-heading"><div><div class="eyebrow">WORKSPACE SETTINGS</div><h1>工作台设置<span class="heading-dot">.</span></h1><p>连接你的工作空间，了解当前运行配置。</p></div></div><div class="settings-grid"><section class="surface"><div class="section-heading"><h2>工作空间访问</h2><KeyRound :size="20" class="muted" /></div><template v-if="health?.public_demo"><div class="public-access-card"><ShieldCheck :size="22" /><div><strong>公开演示已开启</strong><p>打开网页即可体验，无需填写访问码。模型密钥仍只保存在后端，访客无法查看。</p></div></div><p class="small muted">模型接口继续受全局频率与并发限制。公开访客共享临时知识空间，服务休眠或重启后数据清除。</p></template><template v-else><p class="muted">此工作台使用访问码保护，避免其他人消耗你的模型额度。</p><form @submit.prevent="save"><label class="field">工作台访问码<input type="password" v-model="accessToken" autocomplete="off" placeholder="填写 APP_ACCESS_TOKEN 对应的访问码" /></label><p class="small muted">这是工作台访问码，不是模型 API 密钥。仅保存在当前浏览器会话。</p><button class="primary" :disabled="saving"><ShieldCheck :size="16" />{{ saving ? '正在验证连接…' : '保存并连接' }}</button></form></template></section><section class="surface"><div class="section-heading"><h2>运行配置</h2><Server :size="20" class="muted" /></div><dl class="config-list"><div><dt>后端状态</dt><dd><span :class="['tag', health ? '' : 'warning']">{{ health ? '服务在线' : '未连接' }}</span></dd></div><div><dt>访问方式</dt><dd>{{ health?.public_demo ? '公开演示 · 无访问码' : '访问码保护' }}</dd></div><div><dt>模型</dt><dd>{{ health?.model || '连接后查看' }}</dd></div><div><dt>模型密钥</dt><dd>{{ health?.model_configured ? '后端已配置 · 不向浏览器公开' : '尚未配置' }}</dd></div><div><dt>API 地址</dt><dd class="mono">{{ apiBase }}</dd></div><div><dt>知识检索</dt><dd>字符 n-gram 文本匹配</dd></div><div><dt>数据存储</dt><dd>进程内存 · 临时保存</dd></div></dl><button class="quiet" @click="refresh"><RefreshCw :size="15" /> 检查连接</button></section></div><section class="surface about-project"><div class="eyebrow">ABOUT EPOCHFLOW</div><h2>纪流，把 Agent 的过程变得可理解。</h2><p>这是一个基于 Vue 与 Python 的 Agent 学习项目。用真实对话串起意图识别、专业 Agent、知识检索、工具调用和评测，再用清晰的执行记录帮助你理解它们如何协作。</p><div class="about-points"><span><CheckCircle2 :size="16" /> 免费后端实例</span><span><CheckCircle2 :size="16" /> 密钥仅在服务端</span><span><CheckCircle2 :size="16" /> 真实执行记录</span></div><div class="subtle-note">免费服务闲置后会休眠，首次唤醒可能需要约一分钟。服务休眠、重启或重新部署会清除云端会话、上传知识和运行统计。模型调用由服务商单独计费。</div></section></div></template>
